### ISSUE TITLE
Multiple chats and history replay

### ISSUE THREAD

**Issue by pedrosobucki** [pedrosobucki/gpt_script#1]
# TODO
- [ ] Change between multiple chats
- [ ] Replay whole chat conversation
- [ ] Rename chat
- [ ] Set default chat in config file
